[versions]
agp = "8.11.0"
junit = "4.13.2"
junitVersion = "1.2.1"
espressoCore = "3.6.1"
appcompat = "1.7.0"
material = "1.12.0"
activity = "1.10.1"
constraintlayout = "2.2.1"
cameraCore = "1.4.2"
cameraView = "1.4.2"
cameraVideo = "1.4.2"
mlkitVision = "17.0.2"
mlkitFaceDetection = "16.1.5"
mlkitTextRecognition = "16.0.0"
cameraLifecycle = "1.4.2"
cameraCamera2 = "1.4.2"
firebaseBom = "32.8.0"
firebaseDatabase = "20.3.1"
firebaseAuth = "22.3.1"
googleServices = "4.4.1"
firebaseCrashlyticsPlugin = "2.9.9"
poseDetectionCommon = "17.0.0"
poseDetectionAccurate = "17.0.0"
objectDetectionCommon = "18.0.0"
segmentationSelfie = "16.0.0-beta6"
objectDetectionCustom = "17.0.2"
playServicesMlkitTextRecognitionCommon = "19.1.0"
playServicesMlkitTextRecognition = "19.0.1"

[libraries]
junit = { group = "junit", name = "junit", version.ref = "junit" }
ext-junit = { group = "androidx.test.ext", name = "junit", version.ref = "junitVersion" }
espresso-core = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "espressoCore" }
appcompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "appcompat" }
material = { group = "com.google.android.material", name = "material", version.ref = "material" }
activity = { group = "androidx.activity", name = "activity", version.ref = "activity" }
constraintlayout = { group = "androidx.constraintlayout", name = "constraintlayout", version.ref = "constraintlayout" }
camera-core = { group = "androidx.camera", name = "camera-core", version.ref = "cameraCore" }
camera-view = { group = "androidx.camera", name = "camera-view", version.ref = "cameraView" }
camera-video = { group = "androidx.camera", name = "camera-video", version.ref = "cameraVideo" }
mlkit-vision = { group = "com.google.mlkit", name = "vision-common", version.ref = "mlkitVision" }
mlkit-face-detection = { group = "com.google.mlkit", name = "face-detection", version.ref = "mlkitFaceDetection" }
mlkit-text-recognition = { group = "com.google.mlkit", name = "text-recognition", version.ref = "mlkitTextRecognition" }
camera-lifecycle = { group = "androidx.camera", name = "camera-lifecycle", version.ref = "cameraLifecycle" }
camera-camera2 = { group = "androidx.camera", name = "camera-camera2", version.ref = "cameraCamera2" }
firebase-bom = { group = "com.google.firebase", name = "firebase-bom", version.ref = "firebaseBom" }
firebase-database = { group = "com.google.firebase", name = "firebase-database" }
firebase-auth = { group = "com.google.firebase", name = "firebase-auth" }
firebase-crashlytics = { group = "com.google.firebase", name = "firebase-crashlytics" }
firebase-crashlytics-ndk = { group = "com.google.firebase", name = "firebase-crashlytics-ndk" }
pose-detection-common = { group = "com.google.mlkit", name = "pose-detection-common", version.ref = "poseDetectionCommon" }
pose-detection-accurate = { group = "com.google.mlkit", name = "pose-detection-accurate", version.ref = "poseDetectionAccurate" }
object1-detection-common = { group = "com.google.mlkit", name = "object-detection-common", version.ref = "objectDetectionCommon" }
segmentation-selfie = { group = "com.google.mlkit", name = "segmentation-selfie", version.ref = "segmentationSelfie" }
object1-detection-custom = { group = "com.google.mlkit", name = "object-detection-custom", version.ref = "objectDetectionCustom" }
play-services-mlkit-text-recognition-common = { group = "com.google.android.gms", name = "play-services-mlkit-text-recognition-common", version.ref = "playServicesMlkitTextRecognitionCommon" }
play-services-mlkit-text-recognition = { group = "com.google.android.gms", name = "play-services-mlkit-text-recognition", version.ref = "playServicesMlkitTextRecognition" }

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
google-services = { id = "com.google.gms.google-services", version.ref = "googleServices" }
firebase-crashlytics = { id = "com.google.firebase.crashlytics", version.ref = "firebaseCrashlyticsPlugin" }
